# Generated by Django 2.2.24 on 2022-09-01 08:18

from django.db import migrations


def set_building_type(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Flat.objects.filter(construction_year__gte=2015).update(new_building=True)
    Flat.objects.filter(construction_year__lt=2015).update(new_building=False)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20220901_1006'),
    ]

    operations = [
        migrations.RunPython(set_building_type)
    ]
