# Generated by Django 2.2.24 on 2022-09-01 08:18

from django.db import migrations


def set_building_type(apps, schema_editor):
    flats = apps.get_model('property', 'Flat')
    for flat in flats.objects.all():
        if flat.construction_year >= 2015:
            flat.new_building = True
        else:
            flat.new_building = False
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20220901_1006'),
    ]

    operations = [
        migrations.RunPython(set_building_type)
    ]
