# Generated by Django 2.2.24 on 2022-09-02 08:04
import phonenumbers
from django.db import migrations
from phonenumbers import PhoneNumberFormat


def get_pure_phonenumber(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    flats = Flat.objects.all()
    for flat in flats.iterator():
        parsed_number = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        if phonenumbers.is_valid_number_for_region(parsed_number, 'RU'):
            flat.owner_pure_phone = phonenumbers.format_number(parsed_number, PhoneNumberFormat.INTERNATIONAL)
            flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_auto_20220902_1059'),
    ]

    operations = [migrations.RunPython(get_pure_phonenumber)
    ]
