# Generated by Django 2.2.24 on 2022-09-02 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20220902_1232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='owner',
            new_name='owner_name',
        ),
    ]
