# Generated by Django 2.2.24 on 2022-09-05 06:19

from django.db import migrations


def add_flats_to_owner(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for owner in Owner.objects.all():
        flats = Flat.objects.filter(deprecated_owner=owner.owner_name)
        owner.flats.set(flats)


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0016_auto_20220905_1020'),
    ]

    operations = [migrations.RunPython(add_flats_to_owner),
                  ]
